use serde::Serialize;
use std::cell::RefCell;
use std::rc::Rc;
use terrars::*;
use super::provider::ProviderLocalrun;

#[derive(Serialize)]
struct RunData {
    #[serde(skip_serializing_if = "Vec::is_empty")]
    depends_on: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    provider: Option<String>,
    #[serde(skip_serializing_if = "SerdeSkipDefault::is_default")]
    lifecycle: ResourceLifecycle,
    #[serde(skip_serializing_if = "Option::is_none")]
    for_each: Option<String>,
    command: ListField<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    environment: Option<RecField<PrimField<String>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    outputs: Option<ListField<PrimField<String>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    working_dir: Option<PrimField<String>>,
}

struct Run_ {
    shared: StackShared,
    tf_id: String,
    data: RefCell<RunData>,
}

#[derive(Clone)]
pub struct Run(Rc<Run_>);

impl Run {
    fn shared(&self) -> &StackShared {
        &self.0.shared
    }

    pub fn depends_on(self, dep: &impl Referable) -> Self {
        self.0.data.borrow_mut().depends_on.push(dep.extract_ref());
        self
    }

    pub fn set_provider(self, provider: &ProviderLocalrun) -> Self {
        self.0.data.borrow_mut().provider = Some(provider.provider_ref());
        self
    }

    pub fn set_create_before_destroy(self, v: bool) -> Self {
        self.0.data.borrow_mut().lifecycle.create_before_destroy = v;
        self
    }

    pub fn set_prevent_destroy(self, v: bool) -> Self {
        self.0.data.borrow_mut().lifecycle.prevent_destroy = v;
        self
    }

    pub fn ignore_changes_to_all(self) -> Self {
        self.0.data.borrow_mut().lifecycle.ignore_changes = Some(IgnoreChanges::All(IgnoreChangesAll::All));
        self
    }

    pub fn ignore_changes_to_attr(self, attr: impl ToString) -> Self {
        {
            let mut d = self.0.data.borrow_mut();
            if match &mut d.lifecycle.ignore_changes {
                Some(i) => match i {
                    IgnoreChanges::All(_) => {
                        true
                    },
                    IgnoreChanges::Refs(r) => {
                        r.push(attr.to_string());
                        false
                    },
                },
                None => true,
            } {
                d.lifecycle.ignore_changes = Some(IgnoreChanges::Refs(vec![attr.to_string()]));
            }
        }
        self
    }

    pub fn replace_triggered_by_resource(self, r: &impl Resource) -> Self {
        self.0.data.borrow_mut().lifecycle.replace_triggered_by.push(r.extract_ref());
        self
    }

    pub fn replace_triggered_by_attr(self, attr: impl ToString) -> Self {
        self.0.data.borrow_mut().lifecycle.replace_triggered_by.push(attr.to_string());
        self
    }

    #[doc= "Set the field `environment`.\nEnvironment variables; inherits terraform's environment"]
    pub fn set_environment(self, v: impl Into<RecField<PrimField<String>>>) -> Self {
        self.0.data.borrow_mut().environment = Some(v.into());
        self
    }

    #[doc= "Set the field `outputs`.\nPaths to files generated by the command, relative to working directory; the hashes of these are placed in `output_hashes` after execution"]
    pub fn set_outputs(self, v: impl Into<ListField<PrimField<String>>>) -> Self {
        self.0.data.borrow_mut().outputs = Some(v.into());
        self
    }

    #[doc= "Set the field `working_dir`.\nWorking directory in which to run command; defaults to current directory"]
    pub fn set_working_dir(self, v: impl Into<PrimField<String>>) -> Self {
        self.0.data.borrow_mut().working_dir = Some(v.into());
        self
    }

    #[doc= "Get a reference to the value of field `command` after provisioning.\nCommand to run; first element is executable, remaining elements are arguments"]
    pub fn command(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.command", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `environment` after provisioning.\nEnvironment variables; inherits terraform's environment"]
    pub fn environment(&self) -> RecRef<PrimExpr<String>> {
        RecRef::new(self.shared().clone(), format!("{}.environment", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `output_hashes` after provisioning.\nThe hashes of the output files, updated after execution"]
    pub fn output_hashes(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.output_hashes", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `outputs` after provisioning.\nPaths to files generated by the command, relative to working directory; the hashes of these are placed in `output_hashes` after execution"]
    pub fn outputs(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.outputs", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `working_dir` after provisioning.\nWorking directory in which to run command; defaults to current directory"]
    pub fn working_dir(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.working_dir", self.extract_ref()))
    }
}

impl Referable for Run {
    fn extract_ref(&self) -> String {
        format!("{}.{}", self.0.extract_resource_type(), self.0.extract_tf_id())
    }
}

impl Resource for Run { }

impl ToListMappable for Run {
    type O = ListRef<RunRef>;

    fn do_map(self, base: String) -> Self::O {
        self.0.data.borrow_mut().for_each = Some(format!("${{{}}}", base));
        ListRef::new(self.0.shared.clone(), self.extract_ref())
    }
}

impl Resource_ for Run_ {
    fn extract_resource_type(&self) -> String {
        "localrun_run".into()
    }

    fn extract_tf_id(&self) -> String {
        self.tf_id.clone()
    }

    fn extract_value(&self) -> serde_json::Value {
        serde_json::to_value(&self.data).unwrap()
    }
}

pub struct BuildRun {
    pub tf_id: String,
    #[doc= "Command to run; first element is executable, remaining elements are arguments"]
    pub command: ListField<PrimField<String>>,
}

impl BuildRun {
    pub fn build(self, stack: &mut Stack) -> Run {
        let out = Run(Rc::new(Run_ {
            shared: stack.shared.clone(),
            tf_id: self.tf_id,
            data: RefCell::new(RunData {
                depends_on: core::default::Default::default(),
                provider: None,
                lifecycle: core::default::Default::default(),
                for_each: None,
                command: self.command,
                environment: core::default::Default::default(),
                outputs: core::default::Default::default(),
                working_dir: core::default::Default::default(),
            }),
        }));
        stack.add_resource(out.0.clone());
        out
    }
}

pub struct RunRef {
    shared: StackShared,
    base: String,
}

impl Ref for RunRef {
    fn new(shared: StackShared, base: String) -> Self {
        Self {
            shared: shared,
            base: base,
        }
    }
}

impl RunRef {
    fn extract_ref(&self) -> String {
        self.base.clone()
    }

    fn shared(&self) -> &StackShared {
        &self.shared
    }

    #[doc= "Get a reference to the value of field `command` after provisioning.\nCommand to run; first element is executable, remaining elements are arguments"]
    pub fn command(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.command", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `environment` after provisioning.\nEnvironment variables; inherits terraform's environment"]
    pub fn environment(&self) -> RecRef<PrimExpr<String>> {
        RecRef::new(self.shared().clone(), format!("{}.environment", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `output_hashes` after provisioning.\nThe hashes of the output files, updated after execution"]
    pub fn output_hashes(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.output_hashes", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `outputs` after provisioning.\nPaths to files generated by the command, relative to working directory; the hashes of these are placed in `output_hashes` after execution"]
    pub fn outputs(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.outputs", self.extract_ref()))
    }

    #[doc= "Get a reference to the value of field `working_dir` after provisioning.\nWorking directory in which to run command; defaults to current directory"]
    pub fn working_dir(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.working_dir", self.extract_ref()))
    }
}
